# coding: utf-8

# flake8: noqa
"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.author import Author
from openapi_client.models.book import Book
from openapi_client.models.book_create import BookCreate
from openapi_client.models.book_partial_update import BookPartialUpdate
from openapi_client.models.inline_object import InlineObject
from openapi_client.models.update_book_ok import UpdateBookOk

