# coding: utf-8

"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from openapi_client.models.author import Author
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Book(BaseModel):
    """
    
    """ # noqa: E501
    id: StrictInt
    title: StrictStr
    author: Author
    description: StrictStr
    num_of_pages: Annotated[int, Field(strict=True, ge=2)] = Field(alias="numOfPages")
    year: Annotated[int, Field(strict=True, ge=0)]
    cover: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["id", "title", "author", "description", "numOfPages", "year", "cover"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Book from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Book from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "author": Author.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "description": obj.get("description"),
            "numOfPages": obj.get("numOfPages"),
            "year": obj.get("year"),
            "cover": obj.get("cover")
        })
        return _obj


