# coding: utf-8

# flake8: noqa

"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Author",
    "Book",
    "BookCreate",
    "BookPartialUpdate",
    "InlineObject",
    "UpdateBookOk",
]

# import apis into sdk package
from openapi_client.api.books_api import BooksApi as BooksApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.author import Author as Author
from openapi_client.models.book import Book as Book
from openapi_client.models.book_create import BookCreate as BookCreate
from openapi_client.models.book_partial_update import BookPartialUpdate as BookPartialUpdate
from openapi_client.models.inline_object import InlineObject as InlineObject
from openapi_client.models.update_book_ok import UpdateBookOk as UpdateBookOk

