# coding: utf-8

"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.books_api import BooksApi


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_book(self) -> None:
        """Test case for create_book

        Create book
        """
        pass

    def test_delete_book(self) -> None:
        """Test case for delete_book

        Delete book
        """
        pass

    def test_get_book(self) -> None:
        """Test case for get_book

        Get book
        """
        pass

    def test_get_book_list(self) -> None:
        """Test case for get_book_list

        Get book list
        """
        pass

    def test_update_book(self) -> None:
        """Test case for update_book

        Update book
        """
        pass


if __name__ == '__main__':
    unittest.main()
