# coding: utf-8

"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_book_ok import UpdateBookOk

class TestUpdateBookOk(unittest.TestCase):
    """UpdateBookOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateBookOk:
        """Test UpdateBookOk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateBookOk`
        """
        model = UpdateBookOk()
        if include_optional:
            return UpdateBookOk(
                data = openapi_client.models.book.Book(
                    id = 56, 
                    title = '', 
                    author = openapi_client.models.author.Author(
                        id = 56, 
                        name = '', 
                        birth = 0, 
                        num_of_books = 56, ), 
                    description = '', 
                    num_of_pages = 2, 
                    year = 0, 
                    cover = openapi_client.models.cover.cover(), )
            )
        else:
            return UpdateBookOk(
                data = openapi_client.models.book.Book(
                    id = 56, 
                    title = '', 
                    author = openapi_client.models.author.Author(
                        id = 56, 
                        name = '', 
                        birth = 0, 
                        num_of_books = 56, ), 
                    description = '', 
                    num_of_pages = 2, 
                    year = 0, 
                    cover = openapi_client.models.cover.cover(), ),
        )
        """

    def testUpdateBookOk(self):
        """Test UpdateBookOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
