# coding: utf-8

"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_partial_update import BookPartialUpdate

class TestBookPartialUpdate(unittest.TestCase):
    """BookPartialUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookPartialUpdate:
        """Test BookPartialUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookPartialUpdate`
        """
        model = BookPartialUpdate()
        if include_optional:
            return BookPartialUpdate(
                title = '',
                author_id = 56,
                description = '',
                num_of_pages = 56,
                year = 56,
                cover = None
            )
        else:
            return BookPartialUpdate(
                title = '',
                author_id = 56,
                description = '',
                num_of_pages = 56,
                year = 56,
                cover = None,
        )
        """

    def testBookPartialUpdate(self):
        """Test BookPartialUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
