# coding: utf-8

"""
    book management system

    API for book management

    The version of the OpenAPI document: 1337
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inline_object import InlineObject

class TestInlineObject(unittest.TestCase):
    """InlineObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineObject:
        """Test InlineObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineObject`
        """
        model = InlineObject()
        if include_optional:
            return InlineObject(
                message = ''
            )
        else:
            return InlineObject(
                message = '',
        )
        """

    def testInlineObject(self):
        """Test InlineObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
